# ======================
# SERVER
# ======================
server.port=8080

# ======================
# APP NAME
# ======================
spring.application.name=api-gateway

# ======================
# CORS CONFIG
# ======================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*

# ======================
# ROUTES - AUTH SERVICE
# ======================
spring.cloud.gateway.routes[0].id=auth-service-login
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=RequestRateLimiter

# ======================
# ROUTES - USER REGISTER (PUBLIC)
# ======================
spring.cloud.gateway.routes[1].id=user-service-register
spring.cloud.gateway.routes[1].uri=${USER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/register

# ======================
# ROUTES - USER PROTECTED
# ======================
spring.cloud.gateway.routes[2].id=user-service-protected
spring.cloud.gateway.routes[2].uri=${USER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthFilter

# ======================
# JWT CONFIG
# ======================
jwt.secret=${JWT_SECRET:mySecretKey123456789012345678901234567890}

# ======================
# LOGGING
# ======================
logging.level.org.springframework.cloud.gateway=DEBUG
