server.port=8080
spring.application.name=api-gateway

# ======================
# ROUTES
# ======================

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

spring.cloud.gateway.server.webflux.routes[0].id=auth-service-login
spring.cloud.gateway.server.webflux.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[1]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

spring.cloud.gateway.server.webflux.routes[1].id=user-service-register
spring.cloud.gateway.server.webflux.routes[1].uri=http://user-service:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/register
spring.cloud.gateway.server.webflux.routes[1].filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

spring.cloud.gateway.server.webflux.routes[2].id=user-service-protected
spring.cloud.gateway.server.webflux.routes[2].uri=http://user-service:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=JwtAuthFilter
spring.cloud.gateway.server.webflux.routes[2].filters[1]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

# ======================
# CORS
# ======================

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].exposed-headers=*

# ======================
# JWT
# ======================

jwt.secret=mySecretKey123456789012345678901234567890

# ======================
# LOGGING
# ======================

logging.level.org.springframework.cloud.gateway=DEBUG