# Server Port
server.port=8082

# Application Name
spring.application.name=user-service

# Datasource (Docker-friendly)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/authdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:authuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:authpass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.aximly.userservice=DEBUG